export const SPECIES_LOADING = "SPECIES_LOADING";
export const ADD_SPECIES = "ADD_SPECIES";
export const SPECIES_FAILED = "SPECIES_FAILED";

export const GRID_LOADING = "GRID_LOADING";
export const ADD_GRIDS = "ADD_GRIDS";
export const GRIDS_FAILED = "GRIDS_FAILED";

export const SINGLE_GRID_LOADING = "SINGLE_GRID_LOADING";
export const ADD_SINGLE_GRID = "ADD_SINGLE_GRID";
export const SINGLE_GRID_FAILED = "SINGLE_GRID_FAILED";

export const SIGHTINGS_LOADING = "SIGHTINGS_LOADING";
export const ADD_SIGHTINS = "ADD_SIGHTINGS";
export const SIGHTINGS_FAILED = "SIGHTINGS_FAILED";

export const ADD_RAW_SIGHTING = "ADD_RAW_SIGHTING";

export const BIRD_LOADING = "BIRD_LOADING";
export const BIRD_FAILED = "BIRD_FAILED";
export const GET_BIRD = "GET_BIRD";

export const GET_UNRATIFIED_SIGHTING = "GET_UNRATIFIED_SIGHTING"
export const UNRATIFIED_SIGHTING_FAILED = "UNRATIFIED_SIGHTING_FAILED"
export const UNRATIFIED_SIGHTING_LOADING = "UNRATIFIED_SIGHTING_LOADING"

export const VOTE_SIGHTING_FAILED = "VOTE_SIGHTING_FAILED"
export const VOTE_SIGHTING_SUCCESS ="VOTE_SIGHTING_SUCCESS"
export const VOTING= "VOTING"

export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const UPDATE_USER = "UPDATE_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const AUTH_FAILED = "AUTH_FAILED"

export const GET_USER = "GET_USER"
export const GET_USER_FAILED = "GET_USER_FAILED"
export const USER_LOADING  = "USER_LOADING"
export const GET_USER_SIGHTINGS = "GET_USER_SIGHTINGS"
export const USER_SIGHTINGS_FAILED = "GET_USER_SIGHTINGS_FAILED"


