export const SPECIES_LOADING = "SPECIES_LOADING";
export const ADD_SPECIES = "ADD_SPECIES";
export const SPECIES_FAILED = "SPECIES_FAILED";

export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const UPDATE_USER = "UPDATE_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const AUTH_FAILED = "AUTH_FAILED"

